# Generated by Django 4.2.1 on 2023-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=52)),
                ('product_descrip', models.CharField(max_length=300)),
                ('product_img', models.ImageField(upload_to='imageview')),
            ],
        ),
    ]
